### ISSUE TITLE
No way to rediscover microbits after reset or power off

### ISSUE THREAD

**Issue by marukqs** [sandeepmistry/node-bbc-microbit#19]
Hello,

I found no way how to rediscover microbit without restarting the script after pressing reset button on microbit or powering microbit off and then turning it on.

If it is already implemented could you provide an example? All the examples show only discovering of the devices once.

Thanks in advance!

Marijus

**Comment by sandeepmistry** [comment]
Since this module and node-sensortag are both built-on on noble-device,
 you should be able to do something like this node-sensortag example:

https://github.com/sandeepmistry/node-sensortag/blob/master/test-continous-discover-connect.js

Just swap `SensorTag` for `BBCMicrobit` ... 

I'm going to close this for now, as I think your question is answered. Please write here either way with the results and we can re-open this issue as needed.
